services:
  postgres:
    image: docker.io/library/postgres:18.3
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=nextjs-course
    ports:
      - '5435:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', "pg_isready -U postgres -d nextjs-course", ""]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s

  web:
    #########################################################################
    # Настройки сборки Docker-образа.
    #########################################################################
    build:
      # Контекст сборки.
      #
      # Docker будет использовать
      # текущую директорию проекта.
      context: .

      # Путь к Dockerfile.
      dockerfile: ./Dockerfile

    #########################################################################
    # Имя контейнера.
    #########################################################################
    container_name: nextjs-web-app

    #########################################################################
    # Автоматически перезапускать контейнер,
    # если он завершился с ошибкой.
    #########################################################################
    restart: unless-stopped

    #########################################################################
    # Пробрасываем порт приложения.
    #
    # Формат:
    # HOST_PORT:CONTAINER_PORT
    #########################################################################
    ports:
      - "3000:3000"

    #########################################################################
    # Загружаем переменные окружения
    # из файла .env.
    #########################################################################
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:123456@postgres:5432/nextjs-course

    #########################################################################
    # Запускать контейнер только после того,
    # как PostgreSQL станет полностью готов.
    #########################################################################
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
