import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Метаданные приложения, которые Next.js использует для генерации тегов `<title>` и `<meta>`.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Описывает слоты корневого layout.
 *
 * @property children Основной route tree приложения.
 * @property modal Parallel route `@modal`, в который Next.js помещает intercepted modal.
 */
interface RootLayout {
  children: ReactNode;
  modal: ReactNode;
}

/**
 * Корневой layout приложения.
 *
 * Подключает глобальные стили, шрифты Geist, основной контент и parallel slot для модальных
 * маршрутов.
 */
export default function RootLayout({ children, modal }: Readonly<RootLayout>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {children}
        {modal}
      </body>
    </html>
  );
}
