import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Метаданные приложения, которые Next.js использует для генерации тегов `<title>` и `<meta>`.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
};

/**
 * Описывает слоты корневого layout.
 *
 * @property children Основной route tree приложения.
 * @property modal Parallel route `@modal`, в который Next.js помещает intercepted modal.
 */
interface RootLayout {
  children: ReactNode;
  modal: ReactNode;
}

/**
 * Корневой layout приложения.
 *
 * Подключает глобальные стили, шрифты Geist, основной контент и parallel slot для модальных
 * маршрутов.
 *
 * Дополнительно читает заголовок `x-pathname`, который прокидывается из `proxy.ts`. Это пример
 * передачи данных из proxy/middleware-слоя в server component через request headers.
 *
 * @example
 * // proxy.ts:
 * requestHeaders.set("x-pathname", request.nextUrl.pathname);
 *
 * // layout.tsx:
 * const pathname = (await headers()).get("x-pathname");
 */
export default async function RootLayout({ children, modal }: Readonly<RootLayout>) {
  const headersStore = await headers();
  const pathname = headersStore.get("x-pathname") ?? "";
  console.log(`pathname: `, pathname);
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {children}
        {modal}
      </body>
    </html>
  );
}
