import type { Metadata } from "next";

/**
 * Глобальные SEO-метаданные приложения.
 *
 * Next.js автоматически преобразует этот объект
 * в соответствующие meta-теги внутри <head>.
 */
export const metadata: Metadata = {
  /**
   * Краткое описание сайта.
   * Используется поисковыми системами
   * и при предпросмотре ссылок.
   */
  description: "Generated by create next app",

  /**
   * Ключевые слова страницы.
   * Сегодня имеют небольшое влияние на SEO,
   * но поддерживаются для совместимости.
   */
  keywords: ["nextjs", "typescript", "frontend", "web"],

  /**
   * Авторы проекта.
   */
  authors: [
    {
      name: "TeaCoder",
      url: "https://github.com/teacoder52",
    },
  ],

  /**
   * Создатель проекта.
   */
  creator: "Vadim",

  /**
   * Организация, опубликовавшая сайт.
   */
  publisher: "TeaCoder LLC.",

  /**
   * Правила индексирования страницы поисковыми роботами.
   */
  robots: {
    /**
     * Разрешить индексирование страницы.
     */
    index: true,

    /**
     * Разрешить переход по ссылкам на странице.
     */
    follow: true,

    /**
     * Не запрещать кэширование страницы.
     */
    nocache: false,

    /**
     * Отдельные правила для GoogleBot.
     */
    googleBot: {
      /**
       * Разрешить индексирование страницы.
       */
      index: true,

      /**
       * Разрешить переход по ссылкам.
       */
      follow: true,

      /**
       * Разрешить индексирование изображений.
       */
      noimageindex: false,
    },
  },
};

/**
 * Главная страница раздела `/dashboard`.
 *
 * Искусственно задерживает ответ на 3 секунды, чтобы показать работу `loading.tsx`, а затем
 * выводит основной контент дашборда.
 */
export default async function DashboardPage() {
  await new Promise((resolve) => setTimeout(resolve, 3000));

  return (
    <div className="p-4 bg-emerald-50 border-2 border-emerald-500 rounded-md">
      <h1 className="text-xl font-bold text-black">Контент страницы Dashboard</h1>
    </div>
  );
}
